spring:
  application:
    name: tddProject
  datasource:
    url: jdbc:postgresql://localhost:5432/marksismuz #${JDBC_URL}
    username: marksismuz #${JDBC_USERNAME}
    password: itDreamer09721 #${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: public
  liquibase:
    change-log: changelog.yaml
